version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - RDS_DB_URI=postgresql://postgres:postgres@db:5432/approval
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: 'postgres:14.1'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./migrations/scripts/create_approval_db.sql:/docker-entrypoint-initdb.d/create_approval_db.sql
      - ./migrations/scripts/create_approval_schema.sql:/docker-entrypoint-initdb.d/create_approval_schema.sql
